# Generated by Django 2.1.4 on 2018-12-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('case_type', models.CharField(choices=[('1', 'Consultation'), ('2', 'Procedure')], default=1, max_length=256)),
                ('case_specialty', models.CharField(choices=[('1', 'General Practice'), ('2', 'Internal Medicine'), ('3', 'Surgery'), ('4', 'Obstetrics & Gynaecology'), ('5', 'Anesthetics'), ('6', 'Paediatrics'), ('7', 'Mental Health'), ('8', 'Opthalmology'), ('9', 'Orthopedics'), ('10', 'Trauma')], default=1, max_length=256)),
                ('notes', models.TextField(help_text='Enter a description of the case', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=100)),
                ('procedure_type', models.CharField(choices=[('2', 'Diagnostic'), ('1', 'Therapeutic')], default=1, max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Procedures'),
        ),
    ]
