# Generated by Django 2.1.4 on 2019-01-03 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='UID')),
                ('name', models.CharField(max_length=400)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30)),
                ('date_of_contact', models.DateField()),
                ('post_code', models.CharField(max_length=12, verbose_name='Post Code')),
                ('diagnosis', models.CharField(max_length=400, verbose_name='Working Diagnosis')),
                ('supervision',
                 models.CharField(choices=[('1', 'Senior Practitioner'), ('2', 'Supervised'), ('3', 'Observed')],
                                  default=1, max_length=128)),
                ('notes', models.TextField(help_text='Enter a description of the consultation', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('location_type',
                 models.CharField(choices=[('1', 'Hospital'), ('2', 'Community')], default=1, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='UID')),
                ('name', models.CharField(max_length=400)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_contact', models.DateField(verbose_name='Procedure Date')),
                ('sex',
                 models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30, verbose_name='Gender')),
                ('procedure_name', models.CharField(max_length=128)),
                ('procedure_type',
                 models.CharField(choices=[('2', 'Diagnostic'), ('1', 'Therapeutic')], default=1, max_length=256)),
                ('diagnosis', models.CharField(max_length=400, verbose_name='Working Diagnosis')),
                ('supervision',
                 models.CharField(choices=[('1', 'Senior Practitioner'), ('2', 'Supervised'), ('3', 'Observed')],
                                  default=1, max_length=128)),
                ('notes', models.TextField(help_text='Enter a description of the case', max_length=1000)),
                ('location',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_class', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Procedure Classes',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='logbook.Procedure_Class'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Specialty'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Location'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Specialty'),
        ),
    ]
