# Generated by Django 2.1.4 on 2019-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='procedure_type',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='supervision',
            field=models.CharField(
                choices=[('1', 'Senior Practitioner'), ('2', 'Supervised'), ('3', 'Assisted'), ('4', 'Observed')],
                default=1, max_length=128),
        ),
    ]
