# Generated by Django 2.1.4 on 2018-12-18 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_of_contact',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
