# Generated by Django 2.1.4 on 2019-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logbook', '0003_auto_20190109_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='plan',
            field=models.TextField(default='', help_text='Enter the patients post-procedure plan here',
                                   max_length=1000),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.TextField(help_text='Enter a description of the procedure', max_length=1000),
        ),
    ]
