# Generated by Django 2.1.4 on 2019-01-09 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logbook', '0004_auto_20190109_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
