# Generated by Django 2.1.5 on 2019-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_auto_20190109_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.CharField(max_length=400, null=True, verbose_name='Working Diagnosis'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(help_text='Enter a description of the consultation. Do not include the plan.', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='plan',
            field=models.TextField(default='', help_text='Enter the patients plan here', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='post_code',
            field=models.CharField(max_length=12, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='supervision',
            field=models.CharField(choices=[('1', 'Senior Practitioner'), ('2', 'Supervised'), ('3', 'Observed')], default=1, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='uid',
            field=models.CharField(max_length=20, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='diagnosis',
            field=models.CharField(max_length=400, null=True, verbose_name='Working Diagnosis'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.TextField(help_text='Enter a description of the procedure', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='plan',
            field=models.TextField(default='', help_text='Enter the patients post-procedure plan here', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='uid',
            field=models.CharField(max_length=20, null=True, verbose_name='UID'),
        ),
    ]
