# Generated by Django 2.1.4 on 2019-01-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_auto_20190109_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(help_text='Enter a description of the consultation. Do not include the plan.', max_length=20000),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='plan',
            field=models.TextField(default='', help_text='Enter the patients plan here', max_length=10000),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.TextField(help_text='Enter a description of the procedure', max_length=20000),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='plan',
            field=models.TextField(default='', help_text='Enter the patients post-procedure plan here', max_length=10000),
        ),
    ]
