# Generated by Django 2.1.5 on 2019-01-10 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_auto_20190110_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Working Diagnosis'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Location'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter a description of the consultation. Do not include the plan.', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='plan',
            field=models.TextField(blank=True, default='', help_text='Enter the patients plan here', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='post_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Specialty'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='date_of_contact',
            field=models.DateField(blank=True, null=True, verbose_name='Procedure Date'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Location'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter a description of the procedure', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='plan',
            field=models.TextField(blank=True, default='', help_text='Enter the patients post-procedure plan here', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UID'),
        ),
    ]
