# Generated by Django 2.1.5 on 2019-02-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_auto_20190110_2135'),
        ('logbook', '0007_auto_20190110_1020'),
    ]

    operations = [
    ]
