# Generated by Django 2.1.5 on 2019-02-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_merge_20190205_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='plan',
        ),
        migrations.AddField(
            model_name='consultation',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('1', 'Worse'), ('2', 'Unsure'), ('3', 'No change'), ('4', 'Better')], default=3, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Working Diagnosis'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter a description of the consultation.', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='post_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('1', 'Hospital'), ('2', 'General Practice'), ('3', 'Emergency Department')], default=1, max_length=256),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter a description of the procedure', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UID'),
        ),
    ]
