# Generated by Django 2.1.4 on 2019-03-16 02:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_auto_20190205_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, help_text='Enter a description of the procedure', max_length=20000, null=True),
        ),
    ]
